# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dtrainer_pb2 as dtrainer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dtrainer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorStub(object):
    """Coordinator service for worker coordination
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/dtrainer.v1.Coordinator/RegisterWorker',
                request_serializer=dtrainer__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=dtrainer__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/dtrainer.v1.Coordinator/Heartbeat',
                request_serializer=dtrainer__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=dtrainer__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.DeregisterWorker = channel.unary_unary(
                '/dtrainer.v1.Coordinator/DeregisterWorker',
                request_serializer=dtrainer__pb2.DeregisterWorkerRequest.SerializeToString,
                response_deserializer=dtrainer__pb2.DeregisterWorkerResponse.FromString,
                _registered_method=True)
        self.GetShardAssignment = channel.unary_unary(
                '/dtrainer.v1.Coordinator/GetShardAssignment',
                request_serializer=dtrainer__pb2.GetShardAssignmentRequest.SerializeToString,
                response_deserializer=dtrainer__pb2.GetShardAssignmentResponse.FromString,
                _registered_method=True)
        self.ReportShardComplete = channel.unary_unary(
                '/dtrainer.v1.Coordinator/ReportShardComplete',
                request_serializer=dtrainer__pb2.ReportShardCompleteRequest.SerializeToString,
                response_deserializer=dtrainer__pb2.ReportShardCompleteResponse.FromString,
                _registered_method=True)
        self.SyncEpoch = channel.unary_unary(
                '/dtrainer.v1.Coordinator/SyncEpoch',
                request_serializer=dtrainer__pb2.SyncEpochRequest.SerializeToString,
                response_deserializer=dtrainer__pb2.SyncEpochResponse.FromString,
                _registered_method=True)
        self.BarrierWait = channel.unary_unary(
                '/dtrainer.v1.Coordinator/BarrierWait',
                request_serializer=dtrainer__pb2.BarrierWaitRequest.SerializeToString,
                response_deserializer=dtrainer__pb2.BarrierWaitResponse.FromString,
                _registered_method=True)
        self.BeginCheckpoint = channel.unary_unary(
                '/dtrainer.v1.Coordinator/BeginCheckpoint',
                request_serializer=dtrainer__pb2.BeginCheckpointRequest.SerializeToString,
                response_deserializer=dtrainer__pb2.BeginCheckpointResponse.FromString,
                _registered_method=True)
        self.CommitCheckpointShard = channel.unary_unary(
                '/dtrainer.v1.Coordinator/CommitCheckpointShard',
                request_serializer=dtrainer__pb2.CommitCheckpointShardRequest.SerializeToString,
                response_deserializer=dtrainer__pb2.CommitCheckpointShardResponse.FromString,
                _registered_method=True)
        self.FinalizeCheckpoint = channel.unary_unary(
                '/dtrainer.v1.Coordinator/FinalizeCheckpoint',
                request_serializer=dtrainer__pb2.FinalizeCheckpointRequest.SerializeToString,
                response_deserializer=dtrainer__pb2.FinalizeCheckpointResponse.FromString,
                _registered_method=True)


class CoordinatorServicer(object):
    """Coordinator service for worker coordination
    """

    def RegisterWorker(self, request, context):
        """Worker lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShardAssignment(self, request, context):
        """Shard assignment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportShardComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncEpoch(self, request, context):
        """Epoch synchronization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BarrierWait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginCheckpoint(self, request, context):
        """Checkpointing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitCheckpointShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=dtrainer__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=dtrainer__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=dtrainer__pb2.HeartbeatRequest.FromString,
                    response_serializer=dtrainer__pb2.HeartbeatResponse.SerializeToString,
            ),
            'DeregisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterWorker,
                    request_deserializer=dtrainer__pb2.DeregisterWorkerRequest.FromString,
                    response_serializer=dtrainer__pb2.DeregisterWorkerResponse.SerializeToString,
            ),
            'GetShardAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShardAssignment,
                    request_deserializer=dtrainer__pb2.GetShardAssignmentRequest.FromString,
                    response_serializer=dtrainer__pb2.GetShardAssignmentResponse.SerializeToString,
            ),
            'ReportShardComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportShardComplete,
                    request_deserializer=dtrainer__pb2.ReportShardCompleteRequest.FromString,
                    response_serializer=dtrainer__pb2.ReportShardCompleteResponse.SerializeToString,
            ),
            'SyncEpoch': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncEpoch,
                    request_deserializer=dtrainer__pb2.SyncEpochRequest.FromString,
                    response_serializer=dtrainer__pb2.SyncEpochResponse.SerializeToString,
            ),
            'BarrierWait': grpc.unary_unary_rpc_method_handler(
                    servicer.BarrierWait,
                    request_deserializer=dtrainer__pb2.BarrierWaitRequest.FromString,
                    response_serializer=dtrainer__pb2.BarrierWaitResponse.SerializeToString,
            ),
            'BeginCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginCheckpoint,
                    request_deserializer=dtrainer__pb2.BeginCheckpointRequest.FromString,
                    response_serializer=dtrainer__pb2.BeginCheckpointResponse.SerializeToString,
            ),
            'CommitCheckpointShard': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitCheckpointShard,
                    request_deserializer=dtrainer__pb2.CommitCheckpointShardRequest.FromString,
                    response_serializer=dtrainer__pb2.CommitCheckpointShardResponse.SerializeToString,
            ),
            'FinalizeCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeCheckpoint,
                    request_deserializer=dtrainer__pb2.FinalizeCheckpointRequest.FromString,
                    response_serializer=dtrainer__pb2.FinalizeCheckpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dtrainer.v1.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dtrainer.v1.Coordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """Coordinator service for worker coordination
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtrainer.v1.Coordinator/RegisterWorker',
            dtrainer__pb2.RegisterWorkerRequest.SerializeToString,
            dtrainer__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtrainer.v1.Coordinator/Heartbeat',
            dtrainer__pb2.HeartbeatRequest.SerializeToString,
            dtrainer__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtrainer.v1.Coordinator/DeregisterWorker',
            dtrainer__pb2.DeregisterWorkerRequest.SerializeToString,
            dtrainer__pb2.DeregisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShardAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtrainer.v1.Coordinator/GetShardAssignment',
            dtrainer__pb2.GetShardAssignmentRequest.SerializeToString,
            dtrainer__pb2.GetShardAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportShardComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtrainer.v1.Coordinator/ReportShardComplete',
            dtrainer__pb2.ReportShardCompleteRequest.SerializeToString,
            dtrainer__pb2.ReportShardCompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncEpoch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtrainer.v1.Coordinator/SyncEpoch',
            dtrainer__pb2.SyncEpochRequest.SerializeToString,
            dtrainer__pb2.SyncEpochResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BarrierWait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtrainer.v1.Coordinator/BarrierWait',
            dtrainer__pb2.BarrierWaitRequest.SerializeToString,
            dtrainer__pb2.BarrierWaitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtrainer.v1.Coordinator/BeginCheckpoint',
            dtrainer__pb2.BeginCheckpointRequest.SerializeToString,
            dtrainer__pb2.BeginCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitCheckpointShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtrainer.v1.Coordinator/CommitCheckpointShard',
            dtrainer__pb2.CommitCheckpointShardRequest.SerializeToString,
            dtrainer__pb2.CommitCheckpointShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtrainer.v1.Coordinator/FinalizeCheckpoint',
            dtrainer__pb2.FinalizeCheckpointRequest.SerializeToString,
            dtrainer__pb2.FinalizeCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
